//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackMBT.TestSuites {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using System.Reflection;
    using Microsoft.SpecExplorer.Runtime.Testing;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Spec Explorer", "3.5.3146.0")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class StackTestSuite : VsTestClassBase {
        
        public StackTestSuite() {
            this.SetSwitch("ProceedControlTimeout", "100");
            this.SetSwitch("QuiescenceTimeout", "30000");
        }
        
        #region Test Initialization and Cleanup
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize() {
            this.InitializeTestManager();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestCleanup() {
            this.CleanupTestManager();
        }
        #endregion
        
        #region Test Starting in S0
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS0() {
            this.Manager.BeginTest("StackTestSuiteS0");
            this.Manager.Comment("reaching state \'S0\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S1\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S20\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S30\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S40\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S50\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S60\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S70\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S80\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S90\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S100\'");
            this.Manager.Comment("executing step \'call Push(2)\'");
            StackMBT.Implementations.StackImplementation.Push(2);
            this.Manager.Comment("reaching state \'S110\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S118\'");
            this.Manager.Comment("executing step \'call Checker([2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    2,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                1,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            0,
                                                                            ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})}));
            this.Manager.Comment("reaching state \'S126\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S134\'");
            this.Manager.Comment("executing step \'call Push(3)\'");
            StackMBT.Implementations.StackImplementation.Push(3);
            this.Manager.Comment("reaching state \'S142\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S149\'");
            this.Manager.Comment("executing step \'call Checker([3,2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    3,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                2,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            1,
                                                                            this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                        "Head",
                                                                                        "Tail"}, new object[] {
                                                                                        0,
                                                                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})})}));
            this.Manager.Comment("reaching state \'S156\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S163\'");
            this.Manager.Comment("executing step \'call Push(4)\'");
            StackMBT.Implementations.StackImplementation.Push(4);
            this.Manager.Comment("reaching state \'S170\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S175\'");
            this.Manager.Comment("executing step \'call Checker([4,3,2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    4,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                3,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            2,
                                                                            this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                        "Head",
                                                                                        "Tail"}, new object[] {
                                                                                        1,
                                                                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                                    "Head",
                                                                                                    "Tail"}, new object[] {
                                                                                                    0,
                                                                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})})})}));
            this.Manager.Comment("reaching state \'S180\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S185\'");
            this.Manager.Comment("executing step \'call Pop()\'");
            StackMBT.Implementations.StackImplementation.Pop();
            this.Manager.Comment("reaching state \'S190\'");
            this.Manager.Comment("checking step \'return Pop\'");
            this.Manager.Comment("reaching state \'S193\'");
            this.Manager.Comment("executing step \'call Checker([3,2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    3,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                2,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            1,
                                                                            this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                        "Head",
                                                                                        "Tail"}, new object[] {
                                                                                        0,
                                                                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})})}));
            this.Manager.Comment("reaching state \'S196\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S199\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S202\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S203\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S204\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S205\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S10
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS10() {
            this.Manager.BeginTest("StackTestSuiteS10");
            this.Manager.Comment("reaching state \'S10\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S11\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S25\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S35\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S45\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S55\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S65\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S75\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S85\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S95\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S105\'");
            this.Manager.Comment("executing step \'call Push(2)\'");
            StackMBT.Implementations.StackImplementation.Push(2);
            this.Manager.Comment("reaching state \'S115\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S123\'");
            this.Manager.Comment("executing step \'call Checker([2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    2,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                1,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            0,
                                                                            ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})}));
            this.Manager.Comment("reaching state \'S131\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S139\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S147\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S154\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S161\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S168\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S12
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS12() {
            this.Manager.BeginTest("StackTestSuiteS12");
            this.Manager.Comment("reaching state \'S12\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S13\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S26\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S36\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S46\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S56\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S66\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S76\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S86\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S96\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S106\'");
            this.Manager.Comment("executing step \'call Pop()\'");
            StackMBT.Implementations.StackImplementation.Pop();
            this.Manager.Comment("reaching state \'S116\'");
            this.Manager.Comment("checking step \'return Pop\'");
            this.Manager.Comment("reaching state \'S124\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S132\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S140\'");
            this.Manager.Comment("executing step \'call Pop()\'");
            StackMBT.Implementations.StackImplementation.Pop();
            this.Manager.Comment("reaching state \'S148\'");
            this.Manager.Comment("checking step \'return Pop\'");
            this.Manager.Comment("reaching state \'S155\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S162\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S169\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S14
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS14() {
            this.Manager.BeginTest("StackTestSuiteS14");
            this.Manager.Comment("reaching state \'S14\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S15\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S27\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S37\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S47\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S57\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S67\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S77\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S87\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S97\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S107\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S117\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S125\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S133\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S141\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S16
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS16() {
            this.Manager.BeginTest("StackTestSuiteS16");
            this.Manager.Comment("reaching state \'S16\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S17\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S28\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S38\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S48\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S58\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S68\'");
            this.Manager.Comment("executing step \'call Pop()\'");
            StackMBT.Implementations.StackImplementation.Pop();
            this.Manager.Comment("reaching state \'S78\'");
            this.Manager.Comment("checking step \'return Pop\'");
            this.Manager.Comment("reaching state \'S88\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S98\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S108\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S18
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS18() {
            this.Manager.BeginTest("StackTestSuiteS18");
            this.Manager.Comment("reaching state \'S18\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S19\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S29\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S39\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S49\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S59\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S69\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S79\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S89\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S99\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S109\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S2
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS2() {
            this.Manager.BeginTest("StackTestSuiteS2");
            this.Manager.Comment("reaching state \'S2\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S3\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S21\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S31\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S41\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S51\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S61\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S71\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S81\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S91\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S101\'");
            this.Manager.Comment("executing step \'call Push(2)\'");
            StackMBT.Implementations.StackImplementation.Push(2);
            this.Manager.Comment("reaching state \'S111\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S119\'");
            this.Manager.Comment("executing step \'call Checker([2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    2,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                1,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            0,
                                                                            ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})}));
            this.Manager.Comment("reaching state \'S127\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S135\'");
            this.Manager.Comment("executing step \'call Push(3)\'");
            StackMBT.Implementations.StackImplementation.Push(3);
            this.Manager.Comment("reaching state \'S143\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S150\'");
            this.Manager.Comment("executing step \'call Checker([3,2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    3,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                2,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            1,
                                                                            this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                        "Head",
                                                                                        "Tail"}, new object[] {
                                                                                        0,
                                                                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})})}));
            this.Manager.Comment("reaching state \'S157\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S164\'");
            this.Manager.Comment("executing step \'call Push(4)\'");
            StackMBT.Implementations.StackImplementation.Push(4);
            this.Manager.Comment("reaching state \'S171\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S176\'");
            this.Manager.Comment("executing step \'call Checker([4,3,2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    4,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                3,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            2,
                                                                            this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                        "Head",
                                                                                        "Tail"}, new object[] {
                                                                                        1,
                                                                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                                    "Head",
                                                                                                    "Tail"}, new object[] {
                                                                                                    0,
                                                                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})})})}));
            this.Manager.Comment("reaching state \'S181\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S186\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S191\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S194\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S197\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S200\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S4
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS4() {
            this.Manager.BeginTest("StackTestSuiteS4");
            this.Manager.Comment("reaching state \'S4\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S5\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S22\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S32\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S42\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S52\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S62\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S72\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S82\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S92\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S102\'");
            this.Manager.Comment("executing step \'call Push(2)\'");
            StackMBT.Implementations.StackImplementation.Push(2);
            this.Manager.Comment("reaching state \'S112\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S120\'");
            this.Manager.Comment("executing step \'call Checker([2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    2,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                1,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            0,
                                                                            ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})}));
            this.Manager.Comment("reaching state \'S128\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S136\'");
            this.Manager.Comment("executing step \'call Push(3)\'");
            StackMBT.Implementations.StackImplementation.Push(3);
            this.Manager.Comment("reaching state \'S144\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S151\'");
            this.Manager.Comment("executing step \'call Checker([3,2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    3,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                2,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            1,
                                                                            this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                        "Head",
                                                                                        "Tail"}, new object[] {
                                                                                        0,
                                                                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})})}));
            this.Manager.Comment("reaching state \'S158\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S165\'");
            this.Manager.Comment("executing step \'call Pop()\'");
            StackMBT.Implementations.StackImplementation.Pop();
            this.Manager.Comment("reaching state \'S172\'");
            this.Manager.Comment("checking step \'return Pop\'");
            this.Manager.Comment("reaching state \'S177\'");
            this.Manager.Comment("executing step \'call Checker([2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    2,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                1,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            0,
                                                                            ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})}));
            this.Manager.Comment("reaching state \'S182\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S187\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S192\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S195\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S198\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S201\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S6
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS6() {
            this.Manager.BeginTest("StackTestSuiteS6");
            this.Manager.Comment("reaching state \'S6\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S7\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S23\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S33\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S43\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S53\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S63\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S73\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S83\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S93\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S103\'");
            this.Manager.Comment("executing step \'call Push(2)\'");
            StackMBT.Implementations.StackImplementation.Push(2);
            this.Manager.Comment("reaching state \'S113\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S121\'");
            this.Manager.Comment("executing step \'call Checker([2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    2,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                1,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            0,
                                                                            ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})}));
            this.Manager.Comment("reaching state \'S129\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S137\'");
            this.Manager.Comment("executing step \'call Push(3)\'");
            StackMBT.Implementations.StackImplementation.Push(3);
            this.Manager.Comment("reaching state \'S145\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S152\'");
            this.Manager.Comment("executing step \'call Checker([3,2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    3,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                2,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            1,
                                                                            this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                                        "Head",
                                                                                        "Tail"}, new object[] {
                                                                                        0,
                                                                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})})}));
            this.Manager.Comment("reaching state \'S159\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S166\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S173\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S178\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S183\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S188\'");
            this.Manager.EndTest();
        }
        #endregion
        
        #region Test Starting in S8
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        public void StackTestSuiteS8() {
            this.Manager.BeginTest("StackTestSuiteS8");
            this.Manager.Comment("reaching state \'S8\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S9\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S24\'");
            this.Manager.Comment("executing step \'call Push(0)\'");
            StackMBT.Implementations.StackImplementation.Push(0);
            this.Manager.Comment("reaching state \'S34\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S44\'");
            this.Manager.Comment("executing step \'call Checker([0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    0,
                                                    ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})}));
            this.Manager.Comment("reaching state \'S54\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S64\'");
            this.Manager.Comment("executing step \'call Push(1)\'");
            StackMBT.Implementations.StackImplementation.Push(1);
            this.Manager.Comment("reaching state \'S74\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S84\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S94\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S104\'");
            this.Manager.Comment("executing step \'call Push(2)\'");
            StackMBT.Implementations.StackImplementation.Push(2);
            this.Manager.Comment("reaching state \'S114\'");
            this.Manager.Comment("checking step \'return Push\'");
            this.Manager.Comment("reaching state \'S122\'");
            this.Manager.Comment("executing step \'call Checker([2,1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    2,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                1,
                                                                this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                            "Head",
                                                                            "Tail"}, new object[] {
                                                                            0,
                                                                            ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})})}));
            this.Manager.Comment("reaching state \'S130\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S138\'");
            this.Manager.Comment("executing step \'call Pop()\'");
            StackMBT.Implementations.StackImplementation.Pop();
            this.Manager.Comment("reaching state \'S146\'");
            this.Manager.Comment("checking step \'return Pop\'");
            this.Manager.Comment("reaching state \'S153\'");
            this.Manager.Comment("executing step \'call Checker([1,0])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                    "Head",
                                                    "Tail"}, new object[] {
                                                    1,
                                                    this.Make<Microsoft.Xrt.Runtime.RuntimeList<int>>(new string[] {
                                                                "Head",
                                                                "Tail"}, new object[] {
                                                                0,
                                                                ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})})})}));
            this.Manager.Comment("reaching state \'S160\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S167\'");
            this.Manager.Comment("executing step \'call Clear()\'");
            StackMBT.Implementations.StackImplementation.Clear();
            this.Manager.Comment("reaching state \'S174\'");
            this.Manager.Comment("checking step \'return Clear\'");
            this.Manager.Comment("reaching state \'S179\'");
            this.Manager.Comment("executing step \'call Checker([])\'");
            StackMBT.Implementations.StackImplementation.Checker(this.Make<StackMBT.Implementations.StackModelState>(new string[] {
                            "Stack"}, new object[] {
                            this.Make<Microsoft.Modeling.Sequence<int>>(new string[] {
                                        "Rep"}, new object[] {
                                        ((Microsoft.Xrt.Runtime.RuntimeList<int>)(null))})}));
            this.Manager.Comment("reaching state \'S184\'");
            this.Manager.Comment("checking step \'return Checker\'");
            this.Manager.Comment("reaching state \'S189\'");
            this.Manager.EndTest();
        }
        #endregion
    }
}
